
name: Test Pie Dataset

on:
  push:
    branches: [main]
    paths:
      - "dataset_builders/**"
      - "data/datasets/**"
      - "tests/dataset_builders/**"
      - "tests/fixtures/dataset_builders/**"
      - ".github/workflows/test_pie_datasets.yaml"
  pull_request:
    branches: [main, "release/*"]
    paths:
      - "dataset_builders/**"
      - "data/datasets/**"
      - "tests/dataset_builders/**"
      - "tests/fixtures/dataset_builders/**"
      - ".github/workflows/test_pie_datasets.yaml"

jobs:
  directories: # Job that list subdirectories
    runs-on: ubuntu-latest
    outputs:
      dataset: ${{ steps.set-dirs.outputs.dataset }} # generate output name dir by using inner step output
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs # Give it an id to handle to get step outputs in the outputs key above
        run: echo "dataset=$(ls dataset_builders/pie | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"
        # Define step output named dir base on ls command transformed to JSON thanks to jq

  dataset_builder:
    runs-on: ubuntu-latest
    needs: [ directories ] # Depends on previous job
    strategy:
      matrix:
        dataset: ${{fromJson(needs.directories.outputs.dataset)}} # List matrix strategy from directories dynamically
    steps:
      - run: echo ${{matrix.dataset}}
